# dependabot.yml
version: 2
updates:
  # 启用yarn的版本更新
  - package-ecosystem: "yarn"
    # 在根目录下寻找 `package.json` 和 `lock` 文件
    directory: "/"
    # 每周检查 yarn 注册表的更新
    schedule:
      interval: "weekly"
